### ISSUE TITLE
Align with schema.org terms

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#106]
Ellis Pratt has suggested aligning our document types with https://schema.org terms.

Schema.org maintain and promote schemas for structured data on the internet. In particular, they provide tags which we probably should be incorporating technical documentation. It was founded by Google, Microsoft, Yahoo and Yandex and using this apparently increases search indexes.

What do others think about including these tags into our templates?

Any ideas on how we would incorporate such tags into Markdown? Or some other wiki? 

Possible alignment with our 0.1 templates:

api-overview: Maybe: https://schema.org/TechArticle
api-quickstart: Maybe https://schema.org/HowTo
api-reference: https://schema.org/APIReference
discussion: Maybe: https://schema.org/TechArticle
how-to: https://schema.org/HowTo
logging: 
reference:  Maybe: https://schema.org/TechArticle
tutorial: Maybe: https://schema.org/HowTo
..glossary: https://schema.org/DefinedTermSet

**Comment by bjnath** [comment]
As valuable as these pages are to information scientists, they're at best baffling to users looking to fill a hole in their documents. 

Is the idea that they're invisibly incorporated as meta tags for SEO? And/or that they serve us internally as a checklist?

**Comment by camerons** [comment]
Our thinking around templates have moved beyond aligning directly with schema.org, so I'll close this bug as no longer worth tracking.
