### ISSUE TITLE
PR Template Initial

### ISSUE THREAD

**Issue by mgan59** [thegooddocsproject/templates#122]
# PR Template Initial

## Context

As discussed on the weekly-call 05/13/2020, the need for a pull-request template will help us expedite the reviewing process.  There are a few requirements and questions that come to mind.  We should view this work as a living doc, for now we start with a simple PR template.  We can also update it, and if needed we can add more [PR Templates](https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/) for different types.  We had for example discussed a separate repo for `proposals` but realizing we could present a different PR template for Template-Proposals versus Modifications/Repo work.

## Requirements

* PR templates should include a section to indicate the __Issues__ being addressed as those issues include the initial conversation and define the scope of work.
* The PR should also include its own additional _Description__ section that details the work that was ACTUAL done as the scope can sometimes change.
* PR should include a checklist _Type of Change_ -- TBD, but recommend indicating if the PR is copy/type corrections, content additions/deletions.  With this specific PR we are modifying the internals of github's PR system.  I refer to this work as `tooling-support-framework` and usually classify it is __TSF__ work.  This would apply to an additions of _github actions_ as well.

## Example

> Example from one of my project repos that is primarily docs and testing-fixtures.  

![Screen Shot 2020-05-13 at 7 01 23 PM](https://user-images.githubusercontent.com/89339/81874751-8fc00280-954c-11ea-9525-d5f9b3426c47.png)

## Open Questions

* What are the other types of work being scoped? -- aside from copy.  As I'd suggested their is this doc-tooling work.  I've also seen PRS where just files are being renamed/re-organized, so that maybe a scope of work. 
* Thoughts on the Proposals, track here in this repo with a different PR template or make a standalone repo.

**Comment by Dishebh** [comment]
@mgan59 @camerons Can I take up the issue?

**Comment by camerons** [comment]
Thanks for capturing this idea @mgan59. As mentioned, I think it is a good idea.
Re what else to capture. Our project is aiming to be best practice, so approval of a pull request should involve checking what justification can be used to consider this best practice. Ideally this should be captured in the issue, then referenced again in the pull request. For instance, justification might be that you are fixing something to align with our writing style guide.

**Comment by mgan59** [comment]
@camerons 

> __re:__ approval of a pull request should involve checking what justification can be used to consider this best practice ... justification might be that you are fixing something to align with our writing style guide.

Gotcha and see your point.  The example I provided above was a version I was using in an integration-test-suite-repo.  In my repositories that contain feature/production services I typically have a __Context__ section which captures the _WHY_ this change is happening along with the __DETAILS__ which is the stand-in for _how_, typically the specifics.

So similar to your point the __Justification__ is to capture the _why_.  Do we like that as the actual header? Or do we want a different word?  Feel like __Justification__ seems a little strict/harsh?

**Comment by camerons** [comment]
@mgar59, I agree with your suggested framing as WHY, HOW, (and WHAT) - especially as these terms are relatively well understood. Happy to drop the term "Justification" as sounding too strict/harsh.
I think we should still provide some prompts for what should be included in a free text WHY section, such as:
* Aligns with our style guide
* Aligns with thinking or research into best practices (include reference)

**Comment by shreyas1599** [comment]
We also need to ensure that the issues that would be closed by the PR are explicitly linked through the use of certain [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue).

**Comment by mgan59** [comment]
An initial PR has been opened for this work over at #149
