### ISSUE TITLE
Question marks in titles

### ISSUE THREAD

**Issue by shreyas1599** [thegooddocsproject/templates#128]
Going through Google's documentation style guide, I couldn't find a title that was a question. This repo has several titles that are worded as questions. Since titles are not recommended to end with periods - see [this](https://developers.google.com/style/periods#periods_with_headings), I was wondering about other forms of punctuation and noticed none of their titles is worded as questions. 

What does everyone think about changing titles worded as questions to non-questions? (I couldn't find a relevant note about this in their style guide)

Example(see [this](https://github.com/thegooddocsproject/templates/blob/master/discussion/about-discussion.md#when-do-i-need-a-discussion-article)):

Changing this:

> When Do I Need a Discussion Article?

To:

> Purpose of a discussion article 

or

> Need for a discussion article

Or should we just drop the questions marks from all titles? (I'm using a markdown linter on VS code and it highlights the usage of punctuation in a heading with a message recommending not to use it)

**Comment by emckean** [comment]
I don't mind question titles (as long as they don't follow [Betteridge's Law of Headlines](https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines))

The plain language folks suggest using question headings when you know what questions your audience is likely to ask: [https://plainlanguage.gov/guidelines/organize/add-useful-headings/](https://plainlanguage.gov/guidelines/organize/add-useful-headings/)  ... which we do :)

**Comment by shreyas1599** [comment]
Right. Makes sense. But there should be consistency in making use of question marks. Some question titles use it while some don't.

**Comment by emckean** [comment]
I agree that if a title is a question, it should have a question mark :)

**Comment by mgan59** [comment]
I'm a fan of punctuation, and good to tip @shreyas1599 I hadn't realized the vscode markdown linter was flagging punctation, but I see it now [MD026](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md026---trailing-punctuation-in-heading) which links to this [opinion](https://cirosantilli.com/markdown-style-guide#punctuation-at-the-end-of-headers)

> __Rationale:__ Headings are not meant to be full sentences.

Screenshot of the Rules
---
![Screen Shot 2020-06-03 at 6 30 22 AM](https://user-images.githubusercontent.com/89339/83626705-d5785580-a563-11ea-9ad7-c4f408350b79.png)

---

I'm personal 👍 for punctuation, I understand their reasoning.  And maybe periods carry less meaning.  But having a question mark I feel adds context, and why not help your readers when possible.

**Comment by flicstar** [comment]
I am also 👍 for punctuation. I have used question marks judiciously in headings in the past. I hope our tool won't restrict us in doing that - yay for configuring the linter.

**Comment by jaredmorgs** [comment]
+1 for question marks in headings. For example "What is a flibbergidget?"

+1 for other limited punctuation like colons in headings. For example "Example: Testing the flibbergidget"

-1 to periods in headings.

**Comment by jaredmorgs** [comment]
It seems that the only reason this issue was raised is because of the Code linter flagging question marks by default.

https://cirosantilli.com/markdown-style-guide/#punctuation-at-the-end-of-headers this guidance in @mgan59 screenshot does not say anything about question marks being bad.

I think based on this fact, we should close this issue. 
I'll do that, and if there are any objections please reopen the issue.
