### ISSUE TITLE
using a link as link text 

### ISSUE THREAD

**Issue by shreyas1599** [thegooddocsproject/templates#130]
According to the [Google style guide](https://developers.google.com/style/link-text) we shouldn't use the link as link text. An example that violates this is [about-api-reference.md](https://github.com/thegooddocsproject/templates/blob/master/api-reference/about-api-reference.md).

**Comment by jaredmorgs** [comment]
Yep this is correct. We had the same issue in a few documents where I work.
It is not good for accessibility.

**Comment by Dishebh** [comment]
@shreyas1599 can I take up the issue?

**Comment by shreyas1599** [comment]
@Dishebh yeah sure, go ahead

**Comment by Dishebh** [comment]
@shreyas1599 Opened a PR for the issue. Please review.

**Comment by shreyas1599** [comment]
I'm closing this issue as the PR has been merged.
