### ISSUE TITLE
Unclear sentence: This overview explains and engine ...

### ISSUE THREAD

**Issue by shreyas1599** [thegooddocsproject/templates#132]
See Overview Examples Section in [about-overview.md](https://github.com/thegooddocsproject/templates/blob/master/api-overview/about-overview.md). 

Consider the sentence:

> Chrome Native Client. This overview explains and engine that allows C++ to run in the browser...

Is it supposed to be:

> Chrome Native Client. This overview explains _**about an**_ engine that allows C++ to run in the browser...

(or)

> Chrome Native Client. This overview explains _**an**_ engine that allows C++ to run in the browser...

**Comment by jaredmorgs** [comment]
the second example is the correct one.
