### ISSUE TITLE
Implement ventilated prose as a standard for the project

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#135]
Hey folks I'm not certain if we've made a style rule about "one sentence per line" or what's known as ventilated prose or semantic linefeeds?

https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line describes what this is all about.

While that is an Asciidoctor practice I confirm that Markdown supports this for paragraphs also.

I'm finding that reviewing some PRs is becoming difficult because a large block of the text shows an update.
There might be only one word changed in the block. 
Due to a lack of ventilated sentences I waste time trying to find the word changed to verify the fix.

It makes no difference to the person reading the transformed Markdown, but it makes all the difference to the maintainers reviewing textual changes to files.

I can say with confidence that I've been using ventilated prose for at least three years now and would never go back.

**Comment by camerons** [comment]
Jared, I feel that we shouldn't introduce a "one sentence per line" rule into our doc templates.
It would be a rule which works around the limitations with storing data in a wiki format, and the tools which attempt to work around that. (It is a valid convention for that problem.)
It is a case of "first we shape the tools, then the tools shape us".
I feel that we should focus our templates purely on content and words, and try and avoid introducing format decisions into our style guide.
A test of this would be to see whether this recommendation makes sense if we were to translate the template into using a Google Docs format (or some other format).
We could potentially add a separate guide for formatting source docs (for this type of guidance).
So my recommendation would be to close out this suggestion with no action. I'd be interested to hear  the opinion of others.

**Comment by jaredmorgs** [comment]
To be clear, it's more about how you store text in Git rather than any
specific style guideline that we would advocate across all document types.

If someone is copy-pasting from the rendered Markdown view, they won't even
see the formatting.

Jared Morgan
M: +61413005479
Twitter <http://twitter.com/!#/jaredmorgs> | Facebook
<http://facebook.com/jaredmorgs> | GitHub
<https://www.github.com/jaredmorgs>

**Comment by camerons** [comment]
Possibly relevant to this thread, in my day job I've just come across a Markdown style guide, which I think probably fits into the same category. https://github.com/google/styleguide/blob/gh-pages/docguide/style.md
There doesn't seem to be much community activity behind this guide, so we should be careful before considering adopting it.

**Comment by camerons** [comment]
Jared and I discussed this in a video conference and concluded:
* Yes, git changes which are due to changing <enter> and <space> placements is painful and we should try to avoid it.
* It is arguably a tooling problem.
* However, we could address by introducing a Markdown format guide (which a pretty printer could check against and enforce from a git pull request check).
* I, Cameron, will add an item to track this in the "Bounty List" of tasks I'm pulling together. (No link yet).
* So we can close this issue out with no action (beyond the upcoming task description).
