### ISSUE TITLE
Replace some terms with their hyphenated version to make it in sync with the current style guide

### ISSUE THREAD

**Issue by Dishebh** [thegooddocsproject/templates#141]
According to current document writing style and [Google document style guide comprising word list](https://developers.google.com/style/word-list), we should rather use the hyphenated version of some terms like `Step by step` and `Lead in` which are present in `how-to/about-how-to.md` and `how-to/template-how-to.md` docs of the repo.

**Comment by Dishebh** [comment]
cc: @camerons @jaredmorgs @shreyas1599

**Comment by shreyas1599** [comment]
Although I couldn't find step-by-step in the link, step-by-step is used here as an [adjective](https://en.wiktionary.org/wiki/step-by-step) if I'm not wrong so it should include hyphens. While glancing through the link, I also noticed that the use of `above` is not recommended. It looks like we'll have to rephrase many words if we're sticking to the guide.

**Comment by Dishebh** [comment]
+1 to the opinion of @shreyas1599
