### ISSUE TITLE
Write a good Readme for templates repo

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/templates#15]

**Comment by jaredmorgs** [comment]
There may be some work already done on this now my adoc files are merged in. Take a look at the README.adoc in the templates repo and see what you reckon.

**Comment by jaredmorgs** [comment]
@flicstar @archaeogeek @camerons Not sure how we want to do reviews on the content but the readme at the Template root has all the guidance on how to use the four types of templates proposed by me.

**Comment by jaredmorgs** [comment]
I'm going to close this issue off now because the work we're going to do in #20 will supersede this. 

I've pulled out all my content from the README.adoc referenced in this issue and have moved it into the related template files.
