### ISSUE TITLE
Remove the DCO approval check from the templates repo

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/templates#16]

**Comment by camerons** [comment]
Note, the following text is relevant until this DCO check is turned off:

## DCO Licensing signoff

The sign-off is required in order for your pull request to succeed.

To sign your commit, head to your local branch and run:

~~~
git commit --amend --signoff

~~~

**Comment by camerons** [comment]
This issue has been resolved before, so can be closed.
