### ISSUE TITLE
Convert templates from asciidoc to markdown

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#17]
We have previously decided that we would use Markdown as our format [1]. The initial upload of templates from Jared are in asciidoc.

We should change these templates to Markdown, or revisit our original decision.

[1] https://lists.osgeo.org/pipermail/seasonofdocs/2019-July/000421.html

**Comment by jaredmorgs** [comment]
The argument for Asciidoc:

I know we are going to run into a problem that can't be solved by Markdown
without in-line HTML.
I've experienced it before.

There are many things that are not possible with my proposed template
structure in Markdown:

- replaceable variables
- complex tables that aren't HTML
- includes (embedding asciidoc content in other asciidoc content)
- videos natively embedded without HTML passthrough

The interesting thing to remember with these templates that we're proposing
is that they *may not* be copy-pasted verbatim and used.
Folks may take them as inspiration and use the format and guidelines in
whatever tool they are using.

The argument for Markdown is that it could theoretically make contributions
easier.
That is technically true.
But we aren't sure just how much contribution we're going to get on this
project at this point.

It's likely that people who will be contributing will be Tech Writers
anyway, and those folks are going to be familiar with multiple mark-up
languages anyway.
Switching between Markdown and Asciidoc is not a bit ask.

So my strong opinion is that we should use a mark-up language that lets us
convey what we need to convey without being hamstrung.

**Comment by jaredmorgs** [comment]
Based on a great discussion in Slack, we are not going to restrict the type of templates contributed to the Good Docs Project.

But we are going to restrict how we write the Guidelines by keeping them to Markdown and keeping  them generic so they can be applied to different templates contributed to each documentation type directory.

If a template offers advanced functionality based on its mark-up language, these are pointed out in the `about-template.md` file.
