### ISSUE TITLE
Align Contributors' Guides

### ISSUE THREAD

**Issue by Loquacity** [thegooddocsproject/templates#171]
**Describe the bug**
We have several locations with Contributors' Guides, let's align them in the correct place:

* `.github` directory: This is the correct place, so that the repo shows that we have a Contributors' Guide in the Insights tab. However, doing a PR to this directory is a little tricky.
* Templates repo `CONTRIBUTING.md`: This has the right filename, but is only a stub.
* Incubator repo `base-template/contributors-guide.md`: This has content, but is in the wrong location.

**To Reproduce**
1. Go to different locations in the project
1. See different contributors' Guides
1. Be confused

**Expected behavior**
A single guide with comprehensive information, in the `.github` directory, and available in the GH Insights tab.

**Comment by barbaricyawps** [comment]
Thanks for being willing to take this on, @Loquacity . This issue is related to a task needed for the website: https://github.com/thegooddocsproject/website-hugo/issues/22

Would you be willing to let me know what you consolidate so that we can get them up on the website?
