### ISSUE TITLE
How to publish instructions

### ISSUE THREAD

**Issue by arturhefczyc** [thegooddocsproject/templates#184]
Hi,

Templates are great and useful. Thanks for that!

I am not sure if I am missing something but I cannot find any information on how to actually use these templates in practice. In particular on how to publish documents based on these templates. 

Can they be published using GitHub pages? If so, how? 

How to apply some themes, etc...

**Comment by aidanatwork** [comment]
@arturhefczyc We are still fairly early in the project, so we don't have a fully functional workflow developed for using the templates. We have a "Tools" initiative within the project that is working on smoothing out some of these details, integrating the templates with GitHub, popular static-site generators, etc. For now though I think you would just have to manually copy the templates into your pages on whatever publishing platform you are using. Note that even the contents of the templates themselves are still in development. Luckily we have a lot of contributors working on the project and hope to get things more polished this year.

**Comment by aidanatwork** [comment]
I'm closing this out, as it as an excellent suggestion that is already being worked on by the Tools initiative. There is not currently a workflow available for publishing using GitHub pages though.
