### ISSUE TITLE
Use README.md at the project root to define concepts, tasks, and references (content types)

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#20]
Based on the discussion between @cwcromwell and @jaredmorgs in the Templates Slack channel, we need to start with the basics and describe just enough about Concepts, Tasks, and References.

By doing this we can then relate each template type back to these core content types.

**Task**

- Create a single article to live in the /templates README.md
- Describe what a "Concept" is.
- Describe what a "Task" is.
- Describe what a "Reference" is.
- Describe how the Templates repo is set up like a supermarket.
  - three aisles: concept, task, reference
  - template types are like items in each aisle you can use as ingredients for a full docs set
- Use a table to describe where each template type in the repo fits into the concept, task and reference.

**Slack Conversation**

You install the software and then you find out your environment isn’t quite ready. It takes a week to get it ready.
True. We might want to explain the difference between a how-to and a tutorial, to help people find the right one.
We might need a middle level, because I’ve gotten the sense that people want a recipe to put together the documentation for their project.
I feel like we’ll be addressing that if we also have a recipe book that tells you to start your API docs with Reference, quickstart, setup,  and overview. Then add how-to or tutorial to get users to the intermediate level.
Many doc sets lack the Product overview and the setup. So you end up creating those as soon as you start to work on the docs. People don’t know they need them. Ironically, maybe the engineers could write the setup better than us, but they don’t know it’s needed. Installation and setup are the hardest parts of software.
jaredmorgs 08:46
Think of it like a supermarket. You have a drinks aisle, pasta aisle, and frozen foods aisle.
Concept, task, and reference are all aisles and each variation is a different thing you can choose from.
You can combine an number of choices into a docs recipe.
:100:
1

Clarence Cromwell 08:47
Agree.
jaredmorgs 08:47
That might be a good way to introduce it, actually.
Clarence Cromwell 08:54
Daniele Procida makes a good distinction between learning in a tutorial and getting things done in a how-to. I think within the three-aisle system, it would improve each template to explain who it is for and what they are trying to accomplish. Even the product overview has very specific users and goals in mind.

**Comment by jaredmorgs** [comment]
https://github.com/thegooddocsproject/templates/pull/25 needs to be merged before this change can be incorporated.

**Comment by Francesco-Lanciana** [comment]
@jaredmorgs can this be marked as closed?
