### ISSUE TITLE
Create Tutorial template

### ISSUE THREAD

**Issue by aidanatwork** [thegooddocsproject/templates#204]
# Create Tutorial template

### Sub-tasks
1. Create tutorial-template.md and write content for it. You may or may not want to re-use content from the files already in the folder
2. Create tutorial-guide.md and write content for it
3. Create tutorial-theory.md and write content for it. This is any research and conclusions about best practices that support what you are presenting to the end user in the other files. This can be an empty stub file.

There are some old files already in the folder. After finishing the above sub-tasks, it would be great if you could also either remove the old files or create a new task for someone else to do so. 

## Helpful Resources
The Divio Documentation System - Tutorials: https://documentation.divio.com/tutorials/

**Comment by barbaricyawps** [comment]
Marking this issue complete. Great work, @deanna-cs !
