### ISSUE TITLE
Set up the template repository structure

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#21]
Based on the discussion between @cwcromwell and @jaredmorgs in the Templates Slack channel, the following structure was decided upon to make use of both templates.

**Task**

- Implement the following starting point structure
- If templates are already provided by Clarence or Jared, move them into this directory structure.
- If no templates are created yet for the file types, create a bug to track the requirement.

**Agreed Structure**

/templates/
* README.md (covered in #20 )

/templates/overview
* about-overview.md
* template-overview.adoc
* template-overview.md

/templates/discussion
* about-discussion.md
* template-discussions.adoc
* template-discussions.md

/templates/best-practice
* about-best-practice.md
* template-best-practice.adoc
* template-best-practice.md

/templates/tutorial
* about-tutorial.md
* template-tutorial.adoc
* template-tutorial.md

/templates/quickstart
* about-quickstart.md
* template-quickstart.adoc
* template-quickstart.md

/templates/how-to
* about-how-to.md
* template-how-to.adoc
* template-how-to.md

/templates/logging
* about-logging.md
* template-logging.adoc
* template-logging.md

/templates/api-endpoint
* about-api-endpoint.md
* template-api-endpoint.adoc
* template-api-endpoint.md

**Comment by camerons** [comment]
I've moved existing files to fit this structure (now in master). There are still files to create and content to move around within the files.

**Comment by jaredmorgs** [comment]
I have created the files and moved the content around in the #23 commit.
