### ISSUE TITLE
README: broken links

### ISSUE THREAD

**Issue by dufcrule** [thegooddocsproject/templates#247]
I noticed a couple of broken links in the [templates section of the README](https://github.com/thegooddocsproject/templates#the-templates):

<img width="875" alt="Screenshot 2022-05-25 at 08 08 59" src="https://user-images.githubusercontent.com/51410533/170192174-7f67b95b-013b-4c31-9ebf-b7b598ba9a7f.png">

Both the **API Project overview** (https://github.com/thegooddocsproject/templates/blob/dev/about-overview.md) and the **Tutorial** (https://github.com/thegooddocsproject/templates/blob/dev/tutorial/about-tutorial.md) links don't work.

Using relative refs instead of full URLs might fix this. For example:

- `[API Project overview](../api-overview/about-overview.md)`
- `[Tutorial](../tutorial/tutorial-template-guide.md)`

**Comment by Anita-ihuman** [comment]
Can I take up this issue?

**Comment by barbaricyawps** [comment]
@Anita-ihuman , I think there's currently a PR in the repo that fixes it. I just haven't merged it in yet and the person who took the issue forgot to link it and follow our processes for opening PRs.

**Comment by Anita-ihuman** [comment]
Alright then
