### ISSUE TITLE
Should we standardize the front matter (introductory text) that goes at the top of each template file? See the PR for the Our Team template for an example.

### ISSUE THREAD

**Issue by barbaricyawps** [thegooddocsproject/templates#256]

**Comment by heykayla** [comment]
Frontmatter:

- Template: boilerplate text in curly braces
  - Thank you for downloading the [TEMPLATE_NAME] template from The Good Docs Project! We welcome any kind of constructive feedback on our templates. 
- About (AKA guide): boilerplate text in curly braces

7/19/2022
- Started the discussion, but still have more to discuss.
- Will table until the next meeting!

**Comment by heykayla** [comment]
Votes:
- Everyone voted in favor.
- Will hand off to Content Strategy (Felicity) for wording
- Agreed to

**Comment by camerons** [comment]
Rough consensus from meeting:
* "Should we invite feedback?
* Should it go into a new README doc for each template directory? (Probably not)
* Should it go into template doc? (Probably not, keep it simple)
* Should it go in the guide/about? (Probably yes. It aligns with intent of the guide for other guide content)
* Should it be at top or bottom of the guide? (Probably at the bottom. The other content is more important. Open source people know that they can give back.)
* Content of the recommendation: Suggest point back to how to give back. Content strategy group to take an action to suggest text.

Attendees:  Cameron, atroger, Mengmeng, Kayla, Deanna, Felicity
