### ISSUE TITLE
Is the audience type for about-template guidance too narrow?

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#32]
Louise Brooks12:45 14 Nov
SELECTED TEXT:
> They are either the managers responsible for a business decision, or they are engineers who don't know enough about your product to decide whether it can accomplish what they want it to do.

is it really safe to suggest only 2 types of people might assess the product? This whole sentence might be better something like:

There are other potential users who will assess your product to decide if it accomplishes their needs (or something like that) -

**Comment by camerons** [comment]
I like the way you have introduced "For example, ..." to preface the types of personas, and kept the persona descriptions. (I think that these are the most common personas, and it helps understandability.)
