### ISSUE TITLE
Use sentence case in all titles?

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#35]
Feedback suggests we should adopt sentence case in all our titles.

What is our style decision across all templates and the project itself?

**Comment by Francesco-Lanciana** [comment]
After having a look across the templates it seems like we haven't been perfectly consistent on this so definitely good just to adopt a standard and stick with it. 

Did a quick bit of research. [Google](https://developers.google.com/style/capitalization) also seems to advocate sentence case with exceptions for trademarks, keywords, and other terms that are always capitalised a certain way as it's consistent with the capitalization rules for American English, avoids some issues with screen readers treating capital letters differently and is more consistent with unicase languages. 

Has anyone raised any complaints about sentence case? If not I'm happy to go through and update ASAP.

**Comment by jaredmorgs** [comment]
We should stick to Sentence case consistently.

**Comment by camerons** [comment]
I agree to using sentence case. I've raised a motion to confirm our team's support:
https://thegooddocsproject.groups.io/g/main/message/237
@Francesco-Lanciana , thanks for offering to fix this. Assuming there are no objections by 12 Feb 2020, then consider yourself having approval to fix this.

**Comment by BolajiAyodeji** [comment]
Hi @Francesco-Lanciana, are you still working on this or were there any objections?
