### ISSUE TITLE
Define what each template type is in a template family (API)

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#36]
Gloria Ma 12:35 14 Nov
SELECTED TEXT:
Setup information.
Following up on my comment int he README, it would be helpful to define what each template type is upfront. Otherwise, for example, quickstart vs. setup is non-intuitive and we have to click in to see.

**Comment by cwcromwell** [comment]
Agreed. 
The tables on the README page should show that information, but they aren't quite complete. 

This also suggests that we should give some thought to the big picture, in terms of what families and what templates will be included. This project might not make sense if we just collect hundreds or thousands of templates from anyone who wants to submit one. Maybe it should include the least number of templates possible to get the job done.

**Comment by jaredmorgs** [comment]
This issue has aged and is no longer needed.
