### ISSUE TITLE
Should we generalise the descriptions in the quickstart for other types?

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#37]
Michelle Mortimer 12:41 14 Nov

SELECTED TEXT:

>It should describe the easiest way to get the intended results from the API, as opposed to the most optimized production modes or the most advanced uses of the APIShow all

It feels like these are mainly for API and developer docs. If it's intended to be applicable to other types of documentation, perhaps make these descriptions more generic?

**Comment by Francesco-Lanciana** [comment]
Is the intention here to have all quickstart guides start with the same section (i.e. What is a Quickstart)? 
I have created a PR that attempts to address this, if you want to take a look @jaredmorgs
