### ISSUE TITLE
Remove extraneous info in the Main body guidelines.

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#38]
Hannah McKenzie 13:19 14 Nov

https://github.com/thegooddocsproject/templates/blob/master/api-quickstart/about-quickstart.md

SELECTED TEXT:
>And the Quickstart should not contain any additional info that is not needed--because it will be easier to understand if it is as brief as possible.

Suggest shortening sentence: Exclude extraneous information.

Louise Brooks13:43 14 Nov
SELECTED TEXT:
>It should be explaining the basic operations that most users will want to perform on the site, or the operations they will perform when they use the API.

It should explain ...

Louise Brooks13:41 14 Nov
SELECTED TEXT:
>What tasks must be completed (installation, configuring the environment?)

>Another way to describe a quickstart is that it shows potential users what your API can do, rather than tell them; if they follow the steps, any benefits (and the ease of obtaining them) ought to be apparent.

separate bullet point

**Comment by bjnath** [comment]
>  it will be easier to understand if it is as brief as possible.

True, and there's more. People do a quick linear-inch sizing when they see a Quickstart. They lose faith if it looks more like a meal than an appetizer
