### ISSUE TITLE
Define terms "understanding-oriented", "procedural", and "learning" in context of the template

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#40]
Gloria Ma 12:38 14 Nov

https://docs.google.com/document/d/1-Uhy1ZDf-IbkNwtnMnpV6jSK6rISIXR9yjvXfMk0hyQ/edit

SELECTED TEXT:
>understanding-oriented, not procedural or learning

Would probably be good to define these terms somewhere. Maybe use more consistent language in the framework of concept/task/reference, as defined in the README.

For example, I don't know the difference between "understanding" and "learning".

**Comment by Dishebh** [comment]
@jaredmorgs I would like to take up the issue. Can you please share the link to the doc where the issue exists, and do I have to include a glossary for these terms in the same doc?

**Comment by jaredmorgs** [comment]
The text identified as being hard to understand isn't really if you have the context of the source of the term "Discussions". 

https://documentation.divio.com/explanation/ is the updated name given to "Discussion" articles. 

Maybe change the word from "understanding-oriented" (the original explanation provided for this type of documentation) to "explanation-oriented".

>Discussions provide understanding-oriented background information and context-specific knowledge on a particular topic.
The goals of a Discussion article are understanding-oriented, not procedural or learning.

This is the text from the Google Doc. You could probably just reword this opening couple of sentences to:

> Discussions (or explanation) topics explain background information and context-specific knowledge on a particular topic. They explain rather than instruct.
