### ISSUE TITLE
Should we put all the template help text in "about" docs into the templates?

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#41]
Gloria Ma
12:43 14 Nov
Again, I think it would be much much easier to use these templates if the guidelines you've placed in "about-discussion" are directly inside this template.

**Pros**

Potentially better user experience because users wouldn't need to flick between about and template files in their IDE.

**Cons**

Maintenance overhead. If we get multiple examples of template types, we will need to duplicate this same info in all templates. The current approach is essentially single-sourcing the content.

**Solution**

Link out to the about template doc in each template to close the loop?

**Comment by camerons** [comment]
Felicity Brand
13:52 14 Nov
Doc: template-reference
Comment on: "For help with writing and structuring a reference article, see the README.adoc in the template directory for basic guidelines and links."
Felicity comment: I'm not convinced the folk will want to go elsewhere to get the good stuff. I think we need to embed it here.

**Comment by camerons** [comment]
From US/AU weekly meeting discussion, we decided to close this based on:
* There are two personas we want to write to: 1. Open Source Developer - just fill in the template. 2. Tech Writer - wants background information and writing instructions. As such, there is a case for two docs.
* This is really a question that should be picked up by the base template project which Viraji and Lana are leading.

**Comment by viraji** [comment]
Re:This is really a question that should be picked up by the base template project which Viraji and Lana are leading.
Noted, and we will be considering this in the Base Template project.
