### ISSUE TITLE
Remove comment about confluence in the discussion template

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/templates#43]
Delete this:

>// Describe the title of your article by replacing "Discussion template" with the page name you want to publish to in Confluence.

**Comment by camerons** [comment]
There is reference to confluence in template-discussion and template-tutorial. It should be removed in both places:

Paul Foxworthy
14:42 14 Nov
Technology specific, maybe should be more general :)

**Comment by BolajiAyodeji** [comment]
Hi @camerons, I tried looking for the reference to in template-discussion and template-tutorial but couldn't find it. Is it possible that this issue is fixed already? If not, can you provide links to the respective documents for more clarity?
Thank you.

**Comment by jaredmorgs** [comment]
This was a hangover from the initial import and I corrected it myself I think.
