### ISSUE TITLE
Reword "DRY"

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#44]
Anonymous
14:22 14 Nov
Doc: about-reference
Re text: Employ DRY (Don't Repeat Yourself) methods when writing reference documentation.
It's enough to just say "Don't repeat yourself"

**Comment by bjnath** [comment]
The term DRY connects with developers. Partly it shows we speak their language, but also it is a much-discussed topic and rallying cry. We access a vein of culture and thinking if we use the name it's known by.

**Comment by jaredmorgs** [comment]
I originally wrote this template and the only improvement I could make on this issue is to use the full name "Don't Repeat Yourself (DRY)".

**Comment by shreyas1599** [comment]
@jaredmorgs your suggestion seems to be better than removing `DRY`. Although, I still think it doesn't make much of a difference. I personally think we should leave it as it is. Anyway, if you give me the go-ahead, I'll open a PR implementing your suggestion.

**Comment by emckean** [comment]
+1 to Jared's suggestion for keeping DRY to show developer-friendliness. (My preference is always to use the right term, even if it's jargon, AND explain it in context; that way you signal your expertise to those who know the term and educate those who do not. :) )

**Comment by jaredmorgs** [comment]
Nominate me as a reviewer if you like @shreyas1599

**Comment by emckean** [comment]
fixed in PR [#125](https://github.com/thegooddocsproject/templates/pull/125)
