### ISSUE TITLE
Difficult to understand paragraph ...

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#51]
Felicity Brand
13:45 14 Nov
Wow! I find this really hard to read. Is it just me?

Tamanna Sethi
13:51 14 Nov
Yes, I am confused, why are we re-using the content in Overview?

doc: template-howto

Re: 
// Article variables (delete the `// comments` and add in the values)
:description: #Summarise what this how-to article is about in a sentence or two. What you put here is reused in the Overview section and included in HTML description tags.#
:keywords: #These are comma-separated tags, similar to labels#

**Comment by shreyas1599** [comment]
@jaredmorgs Looks like this has been fixed. I couldn't find the exactly referenced text in the issue. Looks like it has been modified. Am I missing something? 

(Also, I hope you don't mind me repeatedly tagging you in issues)

**Comment by jaredmorgs** [comment]
If you can't find it in the source file there's a good chance the problem has been fixed by someone else directly. 

No worries about tagging me in issues @shreyas1599 it gets my attention.
