### ISSUE TITLE
Suggestion: Add links to the parent concept if applicable

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#52]
Tamanna Sethi
13:49 14 Nov
Doc: template-howto

Suggestion: Add links to the parent concept if applicable. For example, it is a 'How-to' about using a toaster, then conceptually there must be an 'About Article' that it can be linked to.

Suggested put under heading: "Overview"

**Comment by jaredmorgs** [comment]
Lana did the work on this one and therefore I'm closing.
