### ISSUE TITLE
Delete: “reused in the Overview section and”

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#53]
Re: #Summarise what this how-to article is about in a sentence or two. What you put here is reused in the Overview section and included in HTML description tags.#

Felicity Brand
13:46 14 Nov
Delete: “reused in the Overview section and”

Felicity Brand
13:46 14 Nov
This is the Overview section, how can it be re-used here? Perhaps a copy/paste error?

**Comment by shreyas1599** [comment]
@camerons I couldn't find this issue in [`template-howto.md`](https://github.com/thegooddocsproject/templates/blob/master/how-to/template-howto.md). Perhaps a non-linked PR must've fixed it?

**Comment by jaredmorgs** [comment]
It must've been fixed as you say @shreyas1599
