### ISSUE TITLE
kebab case vs camel case vs 

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#55]
We are using the term "how-to" and "howto" in how-to/template-howto.
We should make a decision about best practice for this across the project. 
We should also consider other terms, like "thegooddocsproject" vs "TheGoodDocsProject" or "The Good Docs Project", or "quickstart" vs "quick-start".

**Comment by bjnath** [comment]
Why is this issue not long closed? Please hear final arguments and bang the gavel.

**Comment by jaredmorgs** [comment]
hyphenate the how-to is my call

**Comment by camerons** [comment]
@bjnath the reason no decision has been made is because we haven't had someone pushing through the research, ask for decision, implement. (Time constraint).

We have defined the Google Developer's guide as our reference. The word list doesn't reference howto or how-to: https://developers.google.com/style/word-list.
Hyphens are described here: https://developers.google.com/style/hyphens. My interpretation would be how-to from that.

Note, the Microsoft style guide defines "how-to" as the preference. https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/h/how-how-to

So, despite my personal preference, I agree with Jared's suggestion that we stick with "how-to". (If someone wants to implement, go ahead and do so.)
