### ISSUE TITLE
Using tables in step-by-step guide

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#57]
Doc: template-howto
Section: Step-by-step guide

Anonymous
13:38 14 Nov
I would include both the tabular format and the ordered list format here, rather than defaulting to the longer form tabular format
Many tasks don't require a screenshot for every single step, but the whole procedure could be enhanced by one or two key screens.
Felicity Brand
13:51 14 Nov
Cool idea

Tamanna Sethi
13:46 14 Nov
I suggest that we use the simpler ordered list format instead of table as it can be difficult for writers to create, copy, and format tables in certain environments like confluence etc. depending on the platform of delivery. Also, it provides flexibility for steps without screenshots.
Paul Foxworthy
14:17 14 Nov
And think about the content on small screen devices. A step table might not work well.

**Comment by shreyas1599** [comment]
@camerons I think this can be closed. #108 fixes it.

**Comment by jaredmorgs** [comment]
Closing off
