### ISSUE TITLE
Describe the result of step(s) in howto

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#58]
Document: template-howto
Section: Step-by-step guide

Tamanna Sethi
13:46 14 Nov
Add a conclusion to the steps. For example what happens after the user is done following the steps a…
Paul Foxworthy
14:16 14 Nov
Yes. I suggest always summarise and confirm the goal that has been achieved.

**Comment by Dishebh** [comment]
@camerons I would like to work on the issue.

**Comment by camerons** [comment]
Thanks @Dishebh, I've assigned the issue to you.
It might help to review comments in the original doc that was used for reviews: https://drive.google.com/drive/u/1/folders/1He_WbY7qEzCVs1ub9nLQhrL8GOoogy5d
You can turn comments on in the top right of google docs.

**Comment by Dishebh** [comment]
@camerons I opened a PR referencing the issue. Please have a look.

**Comment by Loquacity** [comment]
Merged PR
