### ISSUE TITLE
Add SeeAlso

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#59]
Doc: template-howto
Deepti Korwar
18:37 15 Nov
[Add] A new section called Related resources to capture related how-to guides or articles?

Paul Foxworthy
14:16 14 Nov
... In addition, "Next Steps", "See Also" might be useful

**Comment by camerons** [comment]
Doc:template-tutorial
Tamanna Sethi
14:42 14 Nov
Consider Adding references to How to article template.

**Comment by Dishebh** [comment]
@camerons I would like to work on it. Can you please give some more insights? Do I have to add a `See Also` section at the bottom that refers to other similar sections on the same concept?

**Comment by camerons** [comment]
You can find the source comments in https://drive.google.com/drive/u/1/folders/1He_WbY7qEzCVs1ub9nLQhrL8GOoogy5d
To address this issue, a tech writer should consider the feedback, assess whether it is value, look for other best practices to refer to, and use it to provide a recommendation in the solution.

**Comment by camerons** [comment]
This should probably go in the base template too.

**Comment by barbaricyawps** [comment]
Don't forget that it needs to be included in the raw template, but also the explanation of how to use the template. :)

**Comment by acpkendo** [comment]
The team seemed to agree that this is useful, we'll add to the base template and applicable individual templates. And, as @barbaricyawps mentions above, in the about/how-to file for each.

**Comment by viraji** [comment]
Thanks @acpkendo - as I'm working on another PR for the base template, I can include this as well, myself - shall I?
