### ISSUE TITLE
Tutorials as docs to be stitched together

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#62]
Tamanna Sethi
14:42 14 Nov
... May be describe a tutorial template as a set of different types of documentation that can be stitched together to achieve a broader learning objective. ...

Cameron: I'm hoping Tamanna can expand on this statement.

**Comment by cwcromwell** [comment]
A tutorial is probably a recipe, as opposed to a template. It can combine several templates, either multiple how-tos or concepts and how-tos to help you achieve a goal.

**Comment by acpkendo** [comment]
Based on a discussion with the group, closing this issue as written as Tutorials are existing templates with an existing definition.
The U.S. meeting notes from 12/9 include some information on how modular content will be picked up.
