### ISSUE TITLE
Find alternative to "information progression"

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#70]
Document: https://github.com/thegooddocsproject/templates/blob/master/writing-tips.md
Re: 
> You can use this skeleton to test the information progression in your articles.

Alex Schwarz
13:50 14 Nov
Some assumed knowledge here - would someone unused to writing know why this matters?

**Comment by shreyas1599** [comment]
> You can use this outline to test continuity in your articles.

@camerons Does this make it better?

**Comment by jaredmorgs** [comment]
You could also put this like this:

>Use the outline to gather your thoughts about what main topics you need to tell your readers about in the article.

What do you think about that sort of idea @shreyas1599 and @camerons ?

**Comment by shreyas1599** [comment]
@jaredmorgs `about in the article` seems unnecessary. How about:

> Use the outline to gather your thoughts about the main topics you need to tell your readers.

**Comment by emckean** [comment]
fixed in PR [#125](https://github.com/thegooddocsproject/templates/pull/125)
