### ISSUE TITLE
Typo - adds

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#71]
Doc: https://github.com/thegooddocsproject/templates/blob/master/writing-tips.md

Re:
> Add any links you mention in the body of your discussion topic into the "See also" section. The inline links may get lost in long articles, and scanning for links **add** to your audience's cognitive load.

Hannah McKenzie
13:38 14 Nov
Replace "add" with "adds"

**Comment by shreyas1599** [comment]
@camerons You can close this as per PR #115.
