### ISSUE TITLE
Should we reference DITA

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#73]
Doc: https://github.com/thegooddocsproject/templates/blob/master/README.md

Re: 
> The templates are categorised in line with standard DITA documentation types:

Daniel Fowler
13:41 14 Nov
Not even every documentation writer is familiar with DITA.

**Comment by camerons** [comment]
> **Task**: Gives specific instructions about how to get something done. In practice, Tasks tend to have a specific goal and usually consist of a set of numbered steps that the reader can follow to achieve the goal.

Re the word "Task":
Gloria Ma
13:26 14 Nov
"Procedure" might be a clearer word?

Cameron: I'd suggest we should have a good reason to switch from "task" to "procedure", as "task" is already an established term within the DITA context. Does anyone want to explain why "task" is a more difficult word to understand?

**Comment by jaredmorgs** [comment]
> Cameron: I'd suggest we should have a good reason to switch from "task" to "procedure", as "task" is already an established term within the DITA context. Does anyone want to explain why "task" is a more difficult word to understand?

-1 to changing task to procedure.

**Comment by bjnath** [comment]
> Not even every documentation writer is familiar with DITA.

Mere mention of DITA is going to make users think this job is harder than they thought. 

Let's reap the benefits of the boffin stuff internally but mention it aloud only in a "Further reading" section.

**Comment by aidanatwork** [comment]
-1
I would second avoiding mention of DITA. For many small projects, especially ones without professional tech writers, they may never come within 100 miles of DITA. One of our core use cases is open-source projects maintained solely using GitHub pages. I don't think there is much in the way of DITA capability there.

Separately with regards to "procedure", this is a widely understood term for tech writers. I still think though that for small projects with only developers working on them, there might be value to using more commonplace terms like "Numbered steps to complete a task". But I am less firm about that.

**Comment by acpkendo** [comment]
As the above-listed PR #144 appears to address all the questions/asks in this issue, closing.
