### ISSUE TITLE
Using term/definition

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#74]
Doc: https://github.com/thegooddocsproject/templates/blob/master/README.md

Should we be making use of **term**: definition?  (ie <dt> <dd> format in HTML)
Re:
> **Concept**: Describes how and why things work. Concepts are normally written to help the reader with understanding a technology, prior to using it. 
> **Task**: Gives specific instructions about how to get something done. In practice, Tasks tend to have a specific goal and usually consist of a set of numbered steps that the reader can follow to achieve the goal. 
> **Reference**: Contains structured information or specifications that users need to make a product work. Reference sections should comprehensively catalog data such as functions and their parameters, return codes and error messages.

Louise Brooks
13:26 14 Nov
maybe make these bullet points?

**Comment by Dishebh** [comment]
@camerons so should we make the points above as bullet / ordered list? If we refer to, and follow, the [standard DITA documentation type](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/technicalContent/dita-technicalContent-InformationTypes.html#dita_technicalContent_InformationTypes), we can re-write the points in an ordered list format. What are your views on this?

**Comment by camerons** [comment]
This is a fairly trivial formatting issue, so I'm going to close this no action. If someone can find a standard we should follow which says that we should use a bullet list for listing terms, then I'd be happy for this issue to be reopened and fixed.
