### ISSUE TITLE
Wording - hot and ready to eat

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#76]
Doc: https://github.com/thegooddocsproject/templates/blob/master/README.md

> We like to compare documentation types to aisles in a grocery store. Each aisle includes related templates, which you can think of as ingredients. Use these ingredients in documentation cookbooks to whip up docs that are **hot and ready to eat** for your readers.

Re: hot and ready to eat

Felicity Brand
13:32 14 Nov
yeah nah. :thumbsdown:
Alex Schwarz
13:44 14 Nov
+1

**Comment by shreyas1599** [comment]
@camerons you could just remove `hot and ready to eat`?
> ... Use these ingredients in documentation cookbooks to whip up docs ~~that are hot and ready to eat~~ for your readers.

Does this sound better?

**Comment by mgan59** [comment]
I like short, simple, concise 👍

**Comment by camerons** [comment]
@shreyas1599 Good suggestion, feel free to create a pull request with a fix.
