### ISSUE TITLE
Better explain template and documentation types

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#77]
Doc: https://github.com/thegooddocsproject/templates/blob/master/README.md
Re:
> Templates we currently offer:

Kevin Wongso
14:16 14 Nov
a concept help here will be helpful. At-a-glance people trying to write these for the first time will e.g. not know the difference between tutorial & how-to, or how each template type is meant to be used / their place in the whole doc ecosystem as a whole.

Gloria Ma
13:27 14 Nov
It'd be helpful to add a second column here, with a quick description of each template type.
See also: https://github.com/thegooddocsproject/templates/issues/61

**Comment by mgan59** [comment]
Posting here the current description in the `Readme`

| Template name | Documentation type | Description |
| ------------- | ------------------ | ----------- |
| How-to | Task | Short series of steps for a particular task |
| Tutorial | Concept, Task | A training document for a product or topic |
