### ISSUE TITLE
Idea Jolters coming from a negative perspective

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#80]
Doc: Idea Jolters
https://docs.google.com/document/d/177YrqXs6DzGFeOpey1eGmSMJZ3pWHOpZPil2yIU_x7c/edit#heading=h.e2bcb4siqzkb

Josh Sherwood
13:50 14 Nov
A few of these are coming from a negative perspective. Content for the sake of content isn't always valuable. Can we angle them from the user perspective? Is our content meeting the needs of our users? In what situation would our content be used? - this will then naturally lead to identifying gaps or content that isn't fitting within the user journey.
Erin McKean
14:17 14 Nov
👍

**Comment by bjnath** [comment]
Our immediate base is people whose goal is documentation. The templates will sell themselves as one "aha!" moment after another.

Rallying sulkers should be way down the list. We can save souls outside the church once we've ministered to the souls inside.

**Comment by flicstar** [comment]
The clue is in the name :-) "jolters" are meant to come from a different perspective (in this case, negative) to jolt people into thinking about things another way. Sometimes it's easier to answer what a thing isn't than what it is.
We know that we want content to meet the needs of the user, but we ask a question about "what needs aren't being met" to quickly narrow the focus to identifying gaps.
I'm closing this issue.
