### ISSUE TITLE
Impractical to do API References by hand

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#81]
Doc: Idea Jolters
https://docs.google.com/document/d/177YrqXs6DzGFeOpey1eGmSMJZ3pWHOpZPil2yIU_x7c/edit#heading=h.e2bcb4siqzkb

Daniel Fowler
14:31 14 Nov
Some of these things (e.g. API References) are impractical to do by hand. This would be good to know/communicate.

**Comment by alecthegeek** [comment]
A suggestion.

Provide some examples on how to incorporate API doc tools (e.g. Swagger) into these templates (IMHO the Swagger docs don't explain how to publish the final content)

Can also add information for gRPC tools etc.

**Comment by aidanatwork** [comment]
No clear action can be taken on this, so we will close it out. We'll keep in mind the importance of OAS tools.

**Comment by alecthegeek** [comment]
I have recently incorporated Swagger with Hugo static content. I will be giving a couple of talks to Write the Docs later this year on how I did did it. Maybe that can be used a starting point?
