### ISSUE TITLE
Flip doesn't to does in statement

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#82]
Doc: Idea Jolters
https://docs.google.com/document/d/177YrqXs6DzGFeOpey1eGmSMJZ3pWHOpZPil2yIU_x7c/edit#heading=h.e2bcb4siqzkb

Hannah McKenzie
13:47 14 Nov
This seems confusing. Suggestion:
"How does this apply to your situation? What other situations could it apply to?"

**Comment by Dishebh** [comment]
@camerons I would like to work on the issue. Can you please guide me as to where I can find the necessary docs to make changes to? Thanks!

**Comment by camerons** [comment]
Ah, this is a mistake by me in raising this issue in the first place. This document is not part of our core documentation set, but rather a ideas jolter for a workshop we had last year. I will close this issue with no action.
