### ISSUE TITLE
Change wording: anything => concepts

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#84]
> Sometimes you need to explain in detail how to do a specific task to a user. You don't need to teach them *anything*, but you do need to prescribe a set of sequential steps they must do in that order otherwise they won't be able to use a feature properly.

Paul Foxworthy
13:56 14 Nov
... teach them concepts ...? [instead of "anything"]

**Comment by BolajiAyodeji** [comment]
Hi @camerons,

I assume the document that needs this change is at https://github.com/thegooddocsproject/templates/blob/master/how-to/about-howto.md

Please let me know if I'm wrong, thanks.

**Comment by camerons** [comment]
Yes @BolajiAyodeji , this issue refers to https://github.com/thegooddocsproject/templates/blob/master/how-to/about-howto.md .

Sorry for not mentioning it in the initial ticket.

**Comment by BolajiAyodeji** [comment]
Thanks for confirming.
