### ISSUE TITLE
Audience for howtos

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#87]
doc: https://github.com/thegooddocsproject/templates/blob/master/how-to/about-howto.md

> New users typically don't look for how-to articles when they first start using an application. How-to articles are used by those who have experience with the product and need a specific question answered.

Anonymous
13:55 14 Nov
Is this a common experience? I would expect it to be very common for the first interaction with your doc would be trying to complete a specific task.
I guess it depends on whether the audience is the person who is evaluating / deciding to use a tool vs someone who has to use it, and this is their first attempt and they are stuck.

Paul Foxworthy
13:58 14 Nov
I agree, often your user wants instant gratification. They know they have limited knowledge, but still want to achieve a particular goal

**Comment by shreyas1599** [comment]
@camerons How does this sound?

> How-to articles are used by those who have experience with the product and need a specific question answered. But they are also used by new users who want to instantly solve a problem.

**Comment by jaredmorgs** [comment]
I like where you're going with this @shreyas1599 

Building on your proposed text:

>How-to articles are often used by those who have experience with the product and need a specific question answered. 
New users who want to solve a problem instantly can also benefit from how-to articles providing they are well-written and clearly state any prerequisite knowledge required to complete the how-to.

**Comment by emckean** [comment]
fixed in PR [#125](https://github.com/thegooddocsproject/templates/pull/125)
