### ISSUE TITLE
Unclear "step by step guide"

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#92]
Re: https://github.com/thegooddocsproject/templates/blob/master/how-to/about-howto.md

> When you are explaining steps in a process, it can often be useful to include a screenshot for each part of the process. What can often happen is that when you try to insert a graphic or screenshot into the flow of the procedure, it breaks the procedural content up and makes the instructions difficult to read.

Louise Brooks
14:29 14 Nov
wordy - not sure if this is suggesting that you should use screenshots or that you shouldn't!

so either replace with :
Use a screenshot for each step in a process.

or:
Try to avoid using screenshots for each step in a process because it can make it more difficult to read

> you'll notice the tabular step format in the Step-by-step section of the template.

I don't understand what this means. it needs to be written more simply!
So now do I have to go and read another doc to understand what that means and are you suggesting I use that method or not?
Might be better to give an example here instead and introduce it as: write your steps in a table rather than tabular step format...

> The tabular format allows you to add in your procedural steps right next to the screenshot and reference steps with call-outs.

Louise Brooks
14:35 14 Nov
Using a table means you can easily add a screenshot or callout next to each step.

> If your procedural steps do not require screenshots, then you can default to an ordered list. You can also get this structure in Markdown, but you may need to resort to HTML tables. For Markdown, keep the list as an Ordered list.

again sounds too complicated. Also try to avoid If... then... sentences - it makes it sound very developery!

**Comment by BolajiAyodeji** [comment]
Looks like this is fixed as I could not find the required phrase in the document. Is this issue still valid @camerons?

**Comment by Dishebh** [comment]
@camerons is the issue still up for grabs?

**Comment by camerons** [comment]
This issue is still valid and is up for grabs. Original document reviewed is here:
https://docs.google.com/document/d/1oLWstvvDTHLfZ5QZrDwON1aco0RHdjIv66NblVd7atE/edit#

Another reason for having a screenshot for every key step is that it helps someone who is evaluating the software to see how the software will work - without having to install the software.

@jaredmorgs was the original author of this document, and may have additional feedback.
