### ISSUE TITLE
template for templates

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#94]
From one of our recent team meetings, it was suggested that we should create a template for our templates.
What instructions should we capture in our templates?
How detailed should instructions be?
We probably should define personas.
Etc.

**Comment by jaredmorgs** [comment]
I don't understand what this issue means based on the description.

What is a template of templates?

**Comment by camerons** [comment]
Yes, my description was quite cryptic. Sorry.
I'm proposing we distil the common structure, themes, guidance topics which should be included in each documentation template we write.
I propose that we copy these core elements into a "master template" from which are other documentation templates are derived.

**Comment by cwcromwell** [comment]
The Meta-Template

This is the outline for creating new templates.

It's mainly for the owner and potential contributors to this repo. But contact me by opening an issue before you attempt a pull request. (I'm creating these to contribute to other projects, so you might want to go directly to those projects and offer your contributions.)
Template summary

    Purpose of the document
    Who it is for
    When and why does one need to use this document? (What justifies it as a critical document in the minimum viable doc set?)

Contents
Prerequisites

What knowledge do I need before I begin? What tasks must be completed (installation, configuring the environment?) What this Quickstart will help the reader accomplish Where to get tokens or API keys, etc. if needed
Template body
postrequisites

    What comes next?

More information

    Links to good examples
    Further reading (Links and bibliographic citations that support this document.)

**Comment by camerons** [comment]
I've captured and expanded on this in a larger "Documentation Strategy" piece, which, at time of writing, is just bulleted out to provide a skeleton for discussion.
https://docs.google.com/document/d/1sPaVeFQFEqUs0w0sbvvWz1yW3rZd7Lba2_hNheQG25Y/edit#heading=h.6ym3ww6wrlzo

**Comment by camerons** [comment]
This template material has been merged, so the issue can be closed.
