### ISSUE TITLE
How do we approve PRs?

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/templates#95]
From the 12 December meeting,  it became clear that we need to establish a process on approving our PRs. To get to version 0.1 we took an 'anything goes' approach. NOW we need a bit of rigor. 

We are probably approaching the point of requiring approval from two reviewers to merge a PR. 

It was acknowledged that people have different skillsets - some folks are good with details, and some are good high-level thinkers. Probably something to consider when appointing reviewers.

**Comment by cwcromwell** [comment]
Do you want to require that everyone reads the PRs and at least two people approve them? Do we want to allow just anyone to suggest changes, or only those who are invited to contribute? How much do we benefit from constant suggestions to slightly reword things?

**Comment by barbaricyawps** [comment]
I'm closing this issue because it was resolved when we passed RFC-005, the template contributing process.
