### ISSUE TITLE
Let's have a copy edit

### ISSUE THREAD

**Issue by cwcromwell** [thegooddocsproject/templates#96]
If we want the text of these templates cleaned up, we should find someone who has the time to do a complete copy edit and is willing to use the style book we chose. I'm horrified at the idea of performing an edit by having people from all over the world submit thousands of issues about commas and question marks. 
It creates more work to go through the tickets, and we'll just end up in a global war over the serial comma.

**Comment by Loquacity** [comment]
I am happy to do a copy-edit as part of GSoD 2020, if mentors think it would be valuable. Which style has been chosen?

**Comment by jaredmorgs** [comment]
I believe we've settled on Google Developer Style Guide.

**Comment by jaredmorgs** [comment]
I've assigned this one to you @Loquacity .
